- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: import roles
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq

- name: log nginx conf
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy enxpense reverse proxy
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: install filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat