- name: copy filebeat repo
  ansible.builtin.template:
    src: filebeat.repo
    dest: /etc/yum.repos.d/filebeat.repo

- name: install filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: installed

- name: copy yml configuration
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    enabled: yes
    state: restarted