- name: install filebeat
  ansible.builtin.include_tasks: filebeat.yml
  when: elk_component == "filebeat"

- name: install logstash
  ansible.builtin.include_tasks: logstash.yml
  when: elk_component == "logstash"