    - name: disable mysql which is already there
      ansible.builtin.shell: dnf module disable mysql -y

    - name: copy mysql repo
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: install mysql
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present

    - name: start mysql
      ansible.builtin.systemd:
        name: mysqld
        state: restarted

    - name: setup password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('aws_ssm', 'expense.mysql.mysql_password', region='us-east-1') }}