- name: create a directory
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory

- name: copy configuration file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: install prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.14.0/prometheus-2.14.0.linux-amd64.tar.gz
    dest: /etc/prometheus
    remote_src: yes

- name: copy prometheus service
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: copy grafana repo
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: install grafana
  ansible.builtin.dnf:
    name: grafana
    state: installed

- name: copy grafana service
  ansible.builtin.template:
    src: grafana.service
    dest: /etc/systemd/system/grafana.service

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: restart grafana
  ansible.builtin.systemd:
    name: grafana
    state: restarted