- name: create a directory
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory

- name: copy configuration file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: install prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.14.0/prometheus-2.14.0.linux-amd64.tar.gz
    dest: /etc/prometheus
    remote_src: yes

- name: copy prometheus service
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: copy records configuration
  ansible.builtin.template:
    src: records.yml
    dest: /etc/prometheus/records.yml

- name: copy alert configuration
  ansible.builtin.template:
    src: alerts.yml
    dest: /etc/prometheus/alerts.yml

- name: create directory
  ansible.builtin.file:
    path: /etc/alertmanager
    state: directory

- name: install alert manager
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.26.0/alertmanager-0.26.0.linux-amd64.tar.gz
    dest: /etc/alertmanager
    remote_src: yes

- name: copy alertmanager
  ansible.builtin.template:
    src: alert_manager.yml
    dest: /etc/alertmanager/alert_manager.yml

- name: copy alert manager service
  ansible.builtin.template:
    src: alertmanager.service
    dest: /etc/systemd/system/alertmanager.service

- name: restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
    enabled: yes