route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: sri251375@gmail.com
    from: sri251375@gmail.com
    smarthost: "email-smtp.us-east-1.amazonaws.com:587"
    auth_username: "AKIAWLK5PUPGUIPMSVBN"
    auth_password: "BNZImzhUiTkDpTXImM5TB/6czxrbfIOc4X7Nwjth35z1"
    require_tls: true